### ISSUE TITLE
Can not get 'simple' module to run

### ISSUE THREAD

**Issue by patel99** [spring-guides/tut-spring-boot-oauth2#17]
When I build the simple module using maven and try to access 'localhost:8080' I get the following error:

---------------------------------------------------------------------------------------------------------------------------
```
2016-05-09 02:00:48.027  INFO 9340 --- [           main] com.example.SocialApplication            : Started SocialApplication in 15.058 seconds (JVM running for 16.635)
2016-05-09 02:00:58.506  INFO 9340 --- [nio-8080-exec-1] o.a.coyote.http11.Http11NioProcessor     : Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.

java.lang.IllegalArgumentException: Invalid character (CR or LF) found in method name
	at org.apache.coyote.http11.AbstractNioInputBuffer.parseRequestLine(AbstractNioInputBuffer.java:228) ~[tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1009) ~[tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672) [tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1502) [tomcat-embed-core-8.0.33.jar:8.0.33]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1458) [tomcat-embed-core-8.0.33.jar:8.0.33]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_51]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.0.33.jar:8.0.33]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]

```

---------------------------------------------------------------------------------------------------------------------------

the page automatically got redirected to https:localhost:8080, I tried to use certificate, but then facebook url throws an error for unrecognized application.

**Comment by dsyer** [comment]
It works for me. Can you be more specific, step by step, what you did, and the version of everything you used? The error looks like your browser isn't working.

**Comment by patel99** [comment]
I cloned your repo and imported the project - 'https://github.com/spring-guides/tut-spring-boot-oauth2/tree/master/simple'

And then I simply run the project without making any changes, it used tomcat embedded 8. Tomcat starts without error but when I try to access the localhost:8080 URL, it throws the exception that I mentioned in my first comment. I used chrome, firefox and postman rest client, none of them worked hence browser is not an issue.

As I mentioned it was automatically redirecting me to the https://localhost:8080 instead of http://localhost:8080.

**Comment by dsyer** [comment]
Why would you need to do anything with postman? It's just a normal browser UI.

**Comment by patel99** [comment]
I just tried it to make sure that I am sending a GET request and not POST. Since you mentioned issue may be with browser, I wanted to make sure that browser is not an issue

**Comment by patel99** [comment]
Hi Dave,

I tried to run your code again on my Linux machine(I was running on my windows 10 machine initilaly), and it worked like a charm on it. But it is still not working on my windows machine. Hence I suspect that there are some config issues on my windows machine. If you know in what direction should I look to debug this issue then you are welcome to continue this thread else you can go ahead and close this issue.

Thanks

**Comment by dsyer** [comment]
Maybe your Windows machine has some "smart" security software installed that messes with HTTP requests? There's nothing in that error that looks like it is related to the code here, so I'm going to close this issue. Good luck with finding the answer somewhere else.
