### ISSUE TITLE
JDK 1.7 compatibility?

### ISSUE THREAD

**Issue by anandkr-git** [spring-guides/tut-spring-boot-oauth2#32]
I imported the simple project into my eclipse and tried to run that as a spring boot project however, I see I am getting the below error. Will this not work with JDK 1.7? Is JDK 1.8 a mandatory requirement?

Exception in thread "main" java.lang.UnsupportedClassVersionError: com/example/SocialApplication : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:792)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Comment by anandkr-git** [comment]
Sorry I missed an eclipse setting. It worked.

http://stackoverflow.com/questions/22489398/unsupported-major-minor-version-52-0
