### ISSUE TITLE
Server fails to start at "Testing the OAuth2 Client" part of tutorial

### ISSUE THREAD

**Issue by jrodbx** [spring-guides/tut-spring-boot-oauth2#52]
I'm following the Spring Boot OAuth2 tutorial here:
https://spring.io/guides/tutorials/spring-boot-oauth2/

After completing the section adding:
```
@SpringBootApplication
...
@Order(SecurityProperties.ACCESS_OVERRIDE_ORDER)
public class SocialApplication extends WebSecurityConfigurerAdapter {
  ...
}
```

the server fails to start due to a failed test when running the following command:

`./mvnw package && java -jar target/*.jar`

with the following error message:
```
Caused by: java.lang.IllegalStateException: @Order on WebSecurityConfigurers must be unique. Order of 2147483640 was already used on com.example.SocialApplication$$EnhancerBySpringCGLIB$$c55248b9@56380231, so it cannot be used on org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2SsoDefaultConfiguration$$EnhancerBySpringCGLIB$$f6cdadfe@64f1fd08 too.
	at org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration.setFilterChainProxySecurityConfigurer(WebSecurityConfiguration.java:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:701)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
...
```

**Comment by dsyer** [comment]
Works for me. There is only one filter with an explicit order in the whole code base of this tutorial (https://github.com/spring-guides/tut-spring-boot-oauth2/blob/master/auth-server/src/main/java/com/example/SocialApplication.java#L60) so it doesn't clash with anything. You must have a copy paste error or something.

**Comment by jrodbx** [comment]
Took another look at my project and I see one difference: my ClientApplication and client.yml were under /src/main whereas the repo has them under /src/test (not obvious from the tutorial).  So it looks like having SocialApplication and ClientApplication under /src/main causes the IllegalStateException.  Why is that and is there a way for the two to co-exist under /src/main?

**Comment by dsyer** [comment]
Maybe you have two apps in the same package? Anyway seems like it's not an issue with the tutorial.

**Comment by jrodbx** [comment]
Ah, putting the apps in different packages under /src/main also fixed the issue.  Thanks.

**Comment by afillatre** [comment]
Here's a pull request to fix that, because I found myself in the same situation as well. So this needs to be clarified :)
