### ISSUE TITLE
How to keep google-like-session between multiple client Applications?

### ISSUE THREAD

**Issue by atif92** [spring-guides/tut-spring-boot-oauth2#56]
I cloned this project and decoupled the Auth server and client application, later created a replica of client application to run on different port. Now, what I do not understand is, by logging in to one client application and just refreshing the other client's index page (public page outside security context), it does not let me login inside client Application2 until and unless I do not explicitly login client-app 2. Why these applications does not share session? or how can i achieve it?
example:  Just like how logging into gmail and refreshing youtube's public page let us in.

**Comment by dsyer** [comment]
How do you mean "it does not let me login"? What exactly are you expecting, and what do you see?

**Comment by atif92** [comment]
as i said i created multiple client applications, now when I login to one app and than  by opening any public page of app 2 doesnt logs in that app2, untill i dont excess its private secured page

**Comment by atif92** [comment]
I want it to behave how google, gmail, drive and youtube behaves. we login one app and just visiting any page of other app gives user principle.

**Comment by dsyer** [comment]
And what is it that doesn't work?

**Comment by atif92** [comment]
Sir the auto login on second client app is not working. even if client app one is logged in. Client   app 2 only gets logged in by visiting a page which is under security context. how can i get it aut login, just how youtube, gmail works.

**Comment by dsyer** [comment]
I still don't really understand what you mean y "not working". Maybe you just need to set "autoApprove=true" in the client configurations?

**Comment by atif92** [comment]
I guess that will auto approve the permissions only which is not my issue. i want if one client application  logged in, all other client applications also gets logged in. other applications are only logging in after accessing private pages.  Ill share my code.

**Comment by atif92** [comment]
This is my client Application Code running on localhost:8080

`@SpringBootApplication
@EnableOAuth2Sso
@RestController
public class ClientApplication extends WebSecurityConfigurerAdapter{
	
	@RequestMapping({ "/me", "/user" })
	public Map<String, String> user(Principal principal) {
		OAuth2Authentication oAuth2Authentication =(OAuth2Authentication)SecurityContextHolder.getContext().getAuthentication();
		Authentication userAuthentication = oAuth2Authentication.getUserAuthentication();
		System.out.println("Client-1 oAuth2Authentication =" + oAuth2Authentication.toString());
		System.out.println("Client-1 oAuth2Authentication.Details =" + oAuth2Authentication.getDetails());
		
		Map<String, String> map = new LinkedHashMap<>();
		map.put("name", principal.getName());
		System.out.println("PPPPPPPPPPPPPPPP principal.name ="+principal.getName());
		return map;
	}

	public static void main(String[] args) {
		new SpringApplicationBuilder(ClientApplication.class)
				.properties("spring.config.name=client").run(args);
	}
	
	@Override
	protected void configure(HttpSecurity http) throws Exception {
		//http.addFilterBefore(new SimpleCORSFilter(), ChannelProcessingFilter.class);
		// @formatter:off
		http
		.antMatcher("/**").authorizeRequests()
		.antMatchers("/page1Pub**", "/publicpg**", "/login**", "/index**", "/webjars/**").permitAll()
			.anyRequest().authenticated().and()
			.authorizeRequests().anyRequest().fullyAuthenticated().and()
	    .logout().invalidateHttpSession(true)
	    	.logoutSuccessUrl("/").permitAll()
	    	//.logoutRequestMatcher(new AntPathRequestMatcher("/logout"))
	    	.and().csrf()
	    	.csrfTokenRepository(CookieCsrfTokenRepository.withHttpOnlyFalse());
		http
			.httpBasic().and()
			.authorizeRequests().anyRequest().authenticated().and().csrf().disable();
		// @formatter:on
	}

}

Now I have similar kind of 2nd application running on localhost:8081 so when i login to client1 using localhost:8080/client/login it takes me to auth server and back to home page which is fine as expected but when i open localhost:8081/client/index it does not log me in since index is public page i.e not with in spring security context, my second application only gets logged in when i hit localhost:8081/client/login whereas my second client shall auto login even by visiting the public page, which happens in case of google youtube gmail etc. Hope u understand my question.

`

**Comment by dsyer** [comment]
> Hope u understand my question.

Not really. Can you post all the code in a github project (or maybe your fork of this repo)?

**Comment by atif92** [comment]
Ok let me try another way. Open up your browser and go to www.gmail.com and in another tab open youtube.com. Now login to youtube using your google account, once logged in go back to gmail tab and just hit refresh, this will also log you in to gmail. Now my question is, is that possible using your demos? Because in your demos i always have to hit login again even if my other app are already logged in.

**Comment by dsyer** [comment]
I know how google sites work. What I don't know is what you see that is different (and can't be explained by auto approval or context paths).

**Comment by atif92** [comment]
I read somewhere i have to store session in a session store like redis, which will help me keep same session in browser for my all applications. Cause than if i log into one application client i can get all other applications logged in just by refreshing on their index(public) pages.

**Comment by dsyer** [comment]
Personally I don't like that approach (but you will find a variant of it in this tutorial: https://github.com/spring-guides/tut-spring-security-and-angular-js). If you want a "public" page to trigger a login, then I expect you have to configure it as a protected resource. It's really hard to have this conversation without some concrete code. I wish you'd just post a sample and a clear description of what you expect it to do, and when.

**Comment by atif92** [comment]
Thanks God, that is right what you have understood! I understand that we have to make it protected to achieve it, but somehow the goal is to make it work with public page, since **google apps trigger login from public pages** or if they not than how they do it. I have replicate that scenario. I am running out of time and have to fix this soon or Ill try somehow to post the complete code in git repo.

**Comment by gregturn** [comment]
What do you mean "Google apps trigger login on public page"? If I visit Google.com, no triggering without clicking something. Mail.google.com isn't public but instead protected. 

I'm sure the corner logo tries to access a protected page and the results drives it to either render a login link or my avatar.

**Comment by atif92** [comment]
of course the corner logo might try to access a protected page. The case is to open youtube and google than login one of them and hit refresh on other. Here we do not click the corner circle for logout, just hit the refresh on main public page.

**Comment by atif92** [comment]
Thanks Dave. All i needed was this:

@EnableRedisHttpSession
in all client apps and share the session so that i can login from public pages while other apps were already logged in. Thanks

**Comment by atif92** [comment]
Dear Dave, I just fall into this exception after using Redis with this project can you help me with any workaround of this exception:

org.springframework.data.redis.serializer.SerializationException: Cannot deserialize; nested exception is org.springframework.core.serializer.support.SerializationFailedException: Failed to deserialize payload. Is the byte array a result of corresponding serialization for DefaultDeserializer?; nested exception is java.lang.ClassCastException: cannot assign instance of org.springframework.beans.factory.support.StaticListableBeanFactory to field org.springframework.aop.scope.DefaultScopedObject.beanFactory of type org.springframework.beans.factory.config.ConfigurableBeanFactory in instance of org.springframework.aop.scope.DefaultScopedObject
	at org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.deserialize(JdkSerializationRedisSerializer.java:81) ~[spring-data-redis-1.8.0.RC1.jar:na]
	at org.springframework.data.redis.core.AbstractOperations.deserializeHashValue(AbstractOperations.java:338) ~[spring-data-redis-1.8.0.RC1.jar:na]
	at org.springframework.data.redis.core.AbstractOperations.deserializeHashMap(AbstractOperations.java:282) ~[spring-data-redis-1.8.0.RC1.jar:na]
	at org.springframework.data.redis.core.DefaultHashOperations.entries(DefaultHashOperations.java:227) ~[spring-data-redis-1.8.0.RC1.jar:na]
	at org.springframework.data.redis.core.DefaultBoundHashOperations.entries(DefaultBoundHashOperations.java:102) ~[spring-data-redis-1.8.0.RC1.jar:na]
	at org.springframework.session.data.redis.RedisOperationsSessionRepository.getSession(RedisOperationsSessionRepository.java:432) ~[spring-session-1.3.0.RELEASE.jar:na]
	at org.springframework.session.data.redis.RedisOperationsSessionRepository.onMessage(RedisOperationsSessionRepository.java:519) ~[spring-session-1.3.0.RELEASE.jar:na]
	at org.springframework.data.redis.listener.RedisMessageListenerContainer.executeListener(RedisMessageListenerContainer.java:249) [spring-data-redis-1.8.0.RC1.jar:na]
	at org.springframework.data.redis.listener.RedisMessageListenerContainer.processMessage(RedisMessageListenerContainer.java:239) [spring-data-redis-1.8.0.RC1.jar:na]
	at org.springframework.data.redis.listener.RedisMessageListenerContainer$1.run(RedisMessageListenerContainer.java:967) [spring-data-redis-1.8.0.RC1.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]
Caused by: org.springframework.core.serializer.support.SerializationFailedException: Failed to deserialize payload. Is the byte array a result of corresponding serialization for DefaultDeserializer?; nested exception is java.lang.ClassCastException: cannot assign instance of org.springframework.beans.factory.support.StaticListableBeanFactory to field org.springframework.aop.scope.DefaultScopedObject.beanFactory of type org.springframework.beans.factory.config.ConfigurableBeanFactory in instance of org.springframework.aop.scope.DefaultScopedObject
	at org.springframework.core.serializer.support.DeserializingConverter.convert(DeserializingConverter.java:78) ~[spring-core-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.core.serializer.support.DeserializingConverter.convert(DeserializingConverter.java:36) ~[spring-core-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.deserialize(JdkSerializationRedisSerializer.java:79) ~[spring-data-redis-1.8.0.RC1.jar:na]
	... 10 common frames omitted
Caused by: java.lang.ClassCastException: cannot assign instance of org.springframework.beans.factory.support.StaticListableBeanFactory to field org.springframework.aop.scope.DefaultScopedObject.beanFactory of type org.springframework.beans.factory.config.ConfigurableBeanFactory in instance of org.springframework.aop.scope.DefaultScopedObject
	at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2133) ~[na:1.8.0_66]
	at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1305) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2006) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1707) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1345) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:501) ~[na:1.8.0_66]
	at org.springframework.aop.framework.AdvisedSupport.readObject(AdvisedSupport.java:557) ~[spring-aop-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1900) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) ~[na:1.8.0_66]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371) ~[na:1.8.0_66]
	at org.springframework.core.serializer.DefaultDeserializer.deserialize(DefaultDeserializer.java:70) ~[spring-core-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.core.serializer.support.DeserializingConverter.convert(DeserializingConverter.java:73) ~[spring-core-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	... 12 common frames omitted
