### ISSUE TITLE
org.springframework.security.authentication.BadCredentialsException: Could not obtain access token

### ISSUE THREAD

**Issue by kxg125** [spring-guides/tut-spring-boot-oauth2#60]
Hi,

I tried executing all the examples and got the same timeout error everytime. I did not create a facebook app, created a github one and am using that one for all the examples(changed the application.yml accordingly by replacing the facebook settings with github settings from the github example):
The below logs are from the github example, so i did not change anything apart from the client id/secret:
I get taken to the github login page, and then the authorization page in github. When I click on the authorization page, it times out and I get the Whitelabel error page(type: Unauthorized, status=401)

Some of my logs:
```
...
-07-04 11:13:45.925 DEBUG 14124 --- [nio-8080-exec-2] w.c.HttpSessionSecurityContextRepository : SecurityContext is empty or contents are anonymous - context will not be stored in HttpSession.
2017-07-04 11:13:45.925 DEBUG 14124 --- [nio-8080-exec-2] s.s.w.c.SecurityContextPersistenceFilter : SecurityContextHolder now cleared, as request processing completed
2017-07-04 11:13:45.926 DEBUG 14124 --- [nio-8080-exec-2] o.s.s.web.DefaultRedirectStrategy        : Redirecting to 'https://github.com/login/oauth/authorize?client_id=91e6a79ec8b184738e0b&redirect_uri=http://localhost:8080/login/github&response_type=code&state=GzTk1i'
.....
2017-07-04 11:14:45.716 DEBUG 14124 --- [nio-8080-exec-6] o.s.security.web.FilterChainProxy        : /login/github?code=592d8a6843a6f6963a03&state=GzTk1i at position 6 of 12 in additional filter chain; firing Filter: 'CompositeFilter'
2017-07-04 11:14:45.716 DEBUG 14124 --- [nio-8080-exec-6] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/login/github'; against '/login/facebook'
2017-07-04 11:14:45.716 DEBUG 14124 --- [nio-8080-exec-6] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/login/github'; against '/login/github'
2017-07-04 11:14:45.716 DEBUG 14124 --- [nio-8080-exec-6] uth2ClientAuthenticationProcessingFilter : Request is to process authentication
2017-07-04 11:14:45.745 DEBUG 14124 --- [nio-8080-exec-6] g.c.AuthorizationCodeAccessTokenProvider : Retrieving token from https://github.com/login/oauth/access_token
2017-07-04 11:14:46.031 DEBUG 14124 --- [nio-8080-exec-6] g.c.AuthorizationCodeAccessTokenProvider : Encoding and sending form: {grant_type=[authorization_code], code=[592d8a6843a6f6963a03], redirect_uri=[http://localhost:8080/login/github], client_id=[91e6a79ec8b184738e0b], client_secret=[e3e708743b3f0502368492237608664ed730906d]}
2017-07-04 11:15:07.070 DEBUG 14124 --- [nio-8080-exec-6] uth2ClientAuthenticationProcessingFilter : Authentication request failed: org.springframework.security.authentication.BadCredentialsException: Could not obtain access token

org.springframework.security.authentication.BadCredentialsException: Could not obtain access token
	at org.springframework.security.oauth2.client.filter.OAuth2ClientAuthenticationProcessingFilter.attemptAuthentication(OAuth2ClientAuthenticationProcessingFilter.java:107) ~[spring-security-oauth2-2.0.13.RELEASE.jar:na]
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212) [spring-security-web-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:112) [spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200) [spring-security-web-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:112) [spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	.....
Caused by: org.springframework.security.oauth2.client.resource.OAuth2AccessDeniedException: Error requesting access token.
	at org.springframework.security.oauth2.client.token.OAuth2AccessTokenSupport.retrieveToken(OAuth2AccessTokenSupport.java:145) ~[spring-security-oauth2-2.0.13.RELEASE.jar:na]
	at org.springframework.security.oauth2.client.token.grant.code.AuthorizationCodeAccessTokenProvider.obtainAccessToken(AuthorizationCodeAccessTokenProvider.java:209) ~[spring-security-oauth2-2.0.13.RELEASE.jar:na]
	at org.springframework.security.oauth2.client.token.AccessTokenProviderChain.obtainNewAccessTokenInternal(AccessTokenProviderChain.java:148) ~[spring-security-oauth2-2.0.13.RELEASE.jar:na]
	at org.springframework.security.oauth2.client.token.AccessTokenProviderChain.obtainAccessToken(AccessTokenProviderChain.java:121) ~[spring-security-oauth2-2.0.13.RELEASE.jar:na]
	at org.springframework.security.oauth2.client.OAuth2RestTemplate.acquireAccessToken(OAuth2RestTemplate.java:221) ~[spring-security-oauth2-2.0.13.RELEASE.jar:na]
	at org.springframework.security.oauth2.client.OAuth2RestTemplate.getAccessToken(OAuth2RestTemplate.java:173) ~[spring-security-oauth2-2.0.13.RELEASE.jar:na]
	at org.springframework.security.oauth2.client.filter.OAuth2ClientAuthenticationProcessingFilter.attemptAuthentication(OAuth2ClientAuthenticationProcessingFilter.java:105) ~[spring-security-oauth2-2.0.13.RELEASE.jar:na]
	... 64 common frames omitted
Caused by: org.springframework.web.client.ResourceAccessException: I/O error on POST request for "https://github.com/login/oauth/access_token": Connection timed out: connect; nested exception is java.net.ConnectException: Connection timed out: connect
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:666) ~[spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:621) ~[spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.security.oauth2.client.token.OAuth2AccessTokenSupport.retrieveToken(OAuth2AccessTokenSupport.java:137) ~[spring-security-oauth2-2.0.13.RELEASE.jar:na]
	... 70 common frames omitted
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[na:1.8.0_131]
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[na:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[na:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[na:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_131]
	at java.net.PlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_131]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[na:1.8.0_131]
	at java.net.Socket.connect(Unknown Source) ~[na:1.8.0_131]
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source) ~[na:1.8.0_131]
	at sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source) ~[na:1.8.0_131]
	at sun.net.NetworkClient.doConnect(Unknown Source) ~[na:1.8.0_131]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[na:1.8.0_131]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[na:1.8.0_131]
	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source) ~[na:1.8.0_131]
	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source) ~[na:1.8.0_131]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source) ~[na:1.8.0_131]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[na:1.8.0_131]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[na:1.8.0_131]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[na:1.8.0_131]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source) ~[na:1.8.0_131]
	at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:78) ~[spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:652) ~[spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	... 72 common frames omitted

2017-07-04 11:15:07.073 DEBUG 14124 --- [nio-8080-exec-6] uth2ClientAuthenticationProcessingFilter : Updated SecurityContextHolder to contain null Authentication
```

A few more points in case they are useful:
1. I am using a windows machine/eclipse ide and am starting the SocialApplication.java as a SpringBoot App.
2. I am hitting the app from a new incognito chrome window everytime.
3. I know that I have compromised the client id/secret in the logs. It is just a dummy app, that I will remove once these examples work.
4. I am trying this app from my workspace. Checked the browser: no proxy settings.

I am trying to get started with OAuth2. I have been stuck with this for last 2-3 days. Any help would be very much appreciated. Thanks.

**Comment by dsyer** [comment]
Looks like a network problem to me (like a proxy you need to configure but haven't, or a proxy that's badly configured). It's really nothing that the app can solve in that case. Can you curl `https://github.com/login/oauth/access_token` from the command line? From inside your IDE? From teh browser inside the IDE?

**Comment by kxg125** [comment]
Thanks for the answer.
From my git bash:
```
$ curl https://github.com/login/oauth/access_token
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:41 --:--:--     0cu   rl: (7) Failed to connect to github.com port 443: Timed out
```
From browser inside and outside my ide I get the same 404(This is not the page you are looking for.).

**Comment by kxg125** [comment]
I rechecked my browser proxy settings. There is indeed a bunch of proxy-configurations applied via a .pac file. I tried executing the application in intellij with those proxy settings replicated in the IDE by checking Auto-detect proxy settings and selecting the same .pac file. The results are the same. 

So if I understand correctly, the browser proxy settings is the problem. Am I right? If so what should be my next course of action? Is there a way I can bypass the settings only for these github addresses?

Please note, I tried turning of all the proxy settings on the browser and I was not able to access the internet. Thanks.

**Comment by dsyer** [comment]
Well that suggests, doesn't it, that the browser works and the command line (and JVM) don't?  So you probably have a proxy configured in the browser that doesn't work in other places, or vice versa.

**Comment by kxg125** [comment]
Tried it in a different network and on a different machine and it all works! So most definitively network issues at my workplace. I will try to mimic the browser proxy settings(.pac file) to eclipse at workplace and give it another try. Thank again for your prompt responses.
