### ISSUE TITLE
Can't run this sample by idea ide because of a series exceptions

### ISSUE THREAD

**Issue by andyzhaozhao** [spring-guides/tut-spring-boot-oauth2#87]
**i wan't to run the com.example.SocialApplication. My idea ide and maven are correct.**
**But there is a series of exception:**

```
java.lang.NoClassDefFoundError: org/springframework/expression/ParserContext
	at org.springframework.context.support.AbstractApplicationContext.prepareBeanFactory(AbstractApplicationContext.java:637) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:525) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at com.example.SocialApplication.main(SocialApplication.java:27) [classes/:na]
Caused by: java.lang.ClassNotFoundException: org.springframework.expression.ParserContext
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_144]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_144]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[na:1.8.0_144]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_144]
	... 9 common frames omitted
```

**Comment by dsyer** [comment]
Check your maven cache. Looks like maybe a bad jar file to me.

**Comment by andyzhaozhao** [comment]
_@dsyer Thanks for your reply ._ 
**I have run this window cmd scripts:**
```
@echo off
rem create by andyzhao
set REPOSITORY_PATH=C:\Users\Administrator\.m2\repository
for /f "delims=" %%i in ('dir /b /s "%REPOSITORY_PATH%\*lastUpdated*"') do (
    del /s /q %%i
)
pause
```
**to clean the maven wrong cache.
But the problem still happen.**

**Comment by dsyer** [comment]
I'm not sure if just deleting the `lastUpdated` files will clear the jar cache. You need to delete the bad jar (if that's what it is).

**Comment by andyzhaozhao** [comment]
_@dsyer thank you very mush._
**i don't know how i can find the bad jar. So I deleted all the maven jars in my local maven repository and re-download all of them. the problem was resolved.**
